// This file is automatically generated, but we are making it safe for preview/build.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "";

const fallbackUrl = "https://placeholder.supabase.co";
const fallbackKey = "placeholder-key";

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.warn(
    "Supabase environment variables are missing. Auth/database calls will not work until .env is configured."
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL || fallbackUrl,
  SUPABASE_KEY || fallbackKey,
  {
    auth: {
      storage: typeof window !== "undefined" ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
